name: Build & Deploy Web
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Pub get
        run: flutter pub get

      - name: Build Flutter Web
        run: >
          flutter build web --release --base-href=/
          --dart-define=FB_API_KEY=${{ secrets.FB_API_KEY }}
          --dart-define=FB_APP_ID=${{ secrets.FB_APP_ID }}
          --dart-define=FB_PROJECT_ID=${{ secrets.FB_PROJECT_ID }}
          --dart-define=FB_MESSAGING_SENDER_ID=${{ secrets.FB_MESSAGING_SENDER_ID }}
          --dart-define=FB_AUTH_DOMAIN=${{ secrets.FB_AUTH_DOMAIN }}
          --dart-define=FB_STORAGE_BUCKET=${{ secrets.FB_STORAGE_BUCKET }}
          --dart-define=GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID }}

      - name: Add CNAME
        run: echo "caosbox.com" > build/web/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true
