name: Deploy Web to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    # 👇 Aquí mapeamos los secrets a variables de entorno del job
    env:
      FB_API_KEY: ${{ secrets.FB_API_KEY }}
      FB_APP_ID: ${{ secrets.FB_APP_ID }}
      FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
      FB_MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID }}
      FB_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
      FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
      FB_MEASUREMENT_ID: ${{ secrets.FB_MEASUREMENT_ID }}
      GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'
          channel: 'stable'
          cache: true

      - name: Enable web
        run: flutter config --enable-web

      - name: Sanity check secrets
        shell: bash
        run: |
          set -e
          echo "Comprobando secrets obligatorios…"
          for s in FB_API_KEY FB_APP_ID FB_PROJECT_ID FB_MESSAGING_SENDER_ID FB_AUTH_DOMAIN FB_STORAGE_BUCKET FB_MEASUREMENT_ID GOOGLE_WEB_CLIENT_ID; do
            if [ -z "${!s}" ]; then
              echo "❌ Falta el secret $s"
              exit 1
            else
              echo "✅ $s ok"
            fi
          done

      - name: flutter pub get
        run: flutter pub get

      # Si tu index.html no tiene el placeholder, lo parcheamos sin romper nada
      - name: Ensure <base href> placeholder (idempotent)
        run: |
          if grep -q '<base href="$FLUTTER_BASE_HREF">' web/index.html; then
            echo "base href placeholder ya presente"
          else
            sed -i 's|<base href="/">|<base href="$FLUTTER_BASE_HREF">|' web/index.html || true
          fi

      - name: Build Web
        run: |
          flutter build web \
            --release \
            --pwa-strategy=none \
            --base-href=/ \
            --dart-define=FB_API_KEY="$FB_API_KEY" \
            --dart-define=FB_APP_ID="$FB_APP_ID" \
            --dart-define=FB_PROJECT_ID="$FB_PROJECT_ID" \
            --dart-define=FB_MESSAGING_SENDER_ID="$FB_MESSAGING_SENDER_ID" \
            --dart-define=FB_AUTH_DOMAIN="$FB_AUTH_DOMAIN" \
            --dart-define=FB_STORAGE_BUCKET="$FB_STORAGE_BUCKET" \
            --dart-define=FB_MEASUREMENT_ID="$FB_MEASUREMENT_ID" \
            --dart-define=GOOGLE_WEB_CLIENT_ID="$GOOGLE_WEB_CLIENT_ID"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
