# .github/workflows/deploy.yml
name: Deploy Web to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Pub get
        run: flutter pub get

      - name: Build web (no PWA)
        run: flutter build web --release --base-href=/ --pwa-strategy=none

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          cname: caosbox.com
