name: Build & Deploy Web (caosbox.com)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        run: flutter pub get

      # Build para dominio raíz (caosbox.com) => base-href "/"
      - name: Build web (release)
        run: |
          flutter build web \
            --release \
            --pwa-strategy=none \
            --base-href=/ \
            --dart-define=FB_API_KEY="${FB_API_KEY}" \
            --dart-define=FB_APP_ID="${FB_APP_ID}" \
            --dart-define=FB_PROJECT_ID="${FB_PROJECT_ID}" \
            --dart-define=FB_MESSAGING_SENDER_ID="${FB_MESSAGING_SENDER_ID}" \
            --dart-define=FB_AUTH_DOMAIN="${FB_AUTH_DOMAIN}" \
            --dart-define=FB_STORAGE_BUCKET="${FB_STORAGE_BUCKET}" \
            --dart-define=FB_MEASUREMENT_ID="${FB_MEASUREMENT_ID}" \
            --dart-define=GOOGLE_WEB_CLIENT_ID="${GOOGLE_WEB_CLIENT_ID}"
        env:
          FB_API_KEY: ${{ secrets.FB_API_KEY }}
          FB_APP_ID: ${{ secrets.FB_APP_ID }}
          FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
          FB_MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID }}
          FB_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
          FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
          FB_MEASUREMENT_ID: ${{ secrets.FB_MEASUREMENT_ID }}
          GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}

      # Asegura el CNAME dentro del artefacto publicado
      - name: Add CNAME (caosbox.com)
        run: echo caosbox.com > build/web/CNAME

      # Despliega el contenido de build/web a la rama gh-pages
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/web
          clean: true
          single-commit: true
          commit-message: "deploy: ${GITHUB_SHA}"
