name: Deploy Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web (no PWA)
        run: |
          flutter build web --release --pwa-strategy=none --base-href=/
        env:
          FB_API_KEY: ${{ secrets.FB_API_KEY }}
          FB_APP_ID: ${{ secrets.FB_APP_ID }}
          FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
          FB_MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID }}
          FB_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
          FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
          FB_MEASUREMENT_ID: ${{ secrets.FB_MEASUREMENT_ID }}
          GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}

      - name: Copy 404.html
        run: cp build/web/index.html build/web/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
