name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # ⚠️ Fuerza soporte web SIEMPRE (no usa --overwrite, no toca tu lib/)
      - name: Configure project for web
        run: |
          flutter config --enable-web
          flutter create . --platforms web

      - name: Pub get
        run: flutter pub get

      - name: Build web (dominio raíz)
        run: flutter build web --release --base-href /

      # SPA fallback (evita 404 en GitHub Pages)
      - name: Create 404.html
        run: cp build/web/index.html build/web/404.html

      - name: Deploy to GH Pages (CNAME caosbox.com)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          cname: caosbox.com
