name: Deploy Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      # ⚠️ IMPORTANTE para Flutter Web + Pages:
      # Tu index.html debe tener: <base href="$FLUTTER_BASE_HREF">
      - name: Build Web
        run: flutter build web --release --pwa-strategy=none --base-href=/

      - name: Deploy to gh-pages (preserve CNAME)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          # Esto crea/actualiza el archivo CNAME en la rama gh-pages
          cname: caosbox.com
          keep_files: false
