name: Deploy Flutter Web to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      # Asegura plataforma web (idempotente; no toca tu código Dart)
      - name: Ensure web platform
        run: |
          if [ ! -d "web" ]; then flutter create . --platforms web; fi

      - name: Pub get
        run: flutter pub get

      # Build para dominio raíz caosbox.com
      - name: Build web
        run: flutter build web --release --base-href /

      # SPA fallback: evita 404 al refrescar rutas
      - name: Create 404.html
        run: cp build/web/index.html build/web/404.html

      # Publica y setea CNAME = caosbox.com
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          cname: caosbox.com
