name: pages build and deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Enable web platform
        run: flutter config --enable-web

      - name: Ensure web folder (first time safeguards)
        run: |
          if [ ! -d "web" ]; then
            flutter create . --platforms web
          fi

      - name: Pub get
        run: flutter pub get

      - name: Build web
        run: |
          flutter build web \
            --release \
            --pwa-strategy=none \
            --base-href=/ \
            --source-maps \
            --no-minify \
            --dart-define=FB_API_KEY=${{ secrets.FB_API_KEY }} \
            --dart-define=FB_APP_ID=${{ secrets.FB_APP_ID }} \
            --dart-define=FB_PROJECT_ID=${{ secrets.FB_PROJECT_ID }} \
            --dart-define=FB_MESSAGING_SENDER_ID=${{ secrets.FB_MESSAGING_SENDER_ID }} \
            --dart-define=FB_AUTH_DOMAIN=${{ secrets.FB_AUTH_DOMAIN }} \
            --dart-define=FB_STORAGE_BUCKET=${{ secrets.FB_STORAGE_BUCKET }} \
            --dart-define=FB_MEASUREMENT_ID=${{ secrets.FB_MEASUREMENT_ID }} \
            --dart-define=GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID }}

      - name: Prepare artifact for Pages
        run: |
          mkdir -p build_to_pages
          cp -R build/web/* build_to_pages/
          echo "caosbox.com" > build_to_pages/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build_to_pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
