name: Deploy Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    env:
      FB_API_KEY:               ${{ secrets.FB_API_KEY }}
      FB_APP_ID:                ${{ secrets.FB_APP_ID }}
      FB_PROJECT_ID:            ${{ secrets.FB_PROJECT_ID }}
      FB_MESSAGING_SENDER_ID:   ${{ secrets.FB_MESSAGING_SENDER_ID }}
      FB_AUTH_DOMAIN:           ${{ secrets.FB_AUTH_DOMAIN }}
      FB_STORAGE_BUCKET:        ${{ secrets.FB_STORAGE_BUCKET }}
      FB_MEASUREMENT_ID:        ${{ secrets.FB_MEASUREMENT_ID }}
      GOOGLE_WEB_CLIENT_ID:     ${{ secrets.GOOGLE_WEB_CLIENT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8' # tu versión

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Flutter Web (no SW para evitar cachés rotas)
        run: |
          flutter build web --release --base-href=/ --pwa-strategy=none \
            --dart-define=FB_API_KEY=${FB_API_KEY} \
            --dart-define=FB_APP_ID=${FB_APP_ID} \
            --dart-define=FB_PROJECT_ID=${FB_PROJECT_ID} \
            --dart-define=FB_MESSAGING_SENDER_ID=${FB_MESSAGING_SENDER_ID} \
            --dart-define=FB_AUTH_DOMAIN=${FB_AUTH_DOMAIN} \
            --dart-define=FB_STORAGE_BUCKET=${FB_STORAGE_BUCKET} \
            --dart-define=FB_MEASUREMENT_ID=${FB_MEASUREMENT_ID} \
            --dart-define=GOOGLE_WEB_CLIENT_ID=${GOOGLE_WEB_CLIENT_ID}
          # copiar 404 para SPA
          cp build/web/index.html build/web/404.html || true
          # CNAME para el dominio personalizado
          echo "caosbox.com" > build/web/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true
