name: Deploy Web
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Get packages
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href=/

      # SPA fallback (útil para evitar 404 al navegar directo)
      - name: Add 404 fallback
        run: cp build/web/index.html build/web/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          enable_jekyll: false
          cname: caosbox.com
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
