name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - "lib/**"
      - "web/**"
      - "assets/**"
      - "pubspec.yaml"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Flutter pub get
        run: flutter pub get
      - name: Build Flutter Web
        run: flutter build web --release --base-href=/
      - name: Add CNAME
        run: echo caosbox.com > build/web/CNAME
      - name: Disable Jekyll
        run: touch build/web/.nojekyll
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true
