name: Deploy Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Ensure jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Load Firebase defines from JSON secret
        env:
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
        run: |
          if [ -z "$FIREBASE_JSON" ]; then
            echo "::error::Missing FIREBASE_JSON secret"; exit 1; fi
          echo "$FIREBASE_JSON" | jq .
          echo "FB_API_KEY=$(echo "$FIREBASE_JSON" | jq -r .apiKey)" >> $GITHUB_ENV
          echo "FB_APP_ID=$(echo "$FIREBASE_JSON" | jq -r .appId)" >> $GITHUB_ENV
          echo "FB_PROJECT_ID=$(echo "$FIREBASE_JSON" | jq -r .projectId)" >> $GITHUB_ENV
          echo "FB_MESSAGING_SENDER_ID=$(echo "$FIREBASE_JSON" | jq -r .messagingSenderId)" >> $GITHUB_ENV
          echo "FB_AUTH_DOMAIN=$(echo "$FIREBASE_JSON" | jq -r .authDomain)" >> $GITHUB_ENV
          echo "FB_STORAGE_BUCKET=$(echo "$FIREBASE_JSON" | jq -r .storageBucket)" >> $GITHUB_ENV
          echo "FB_MEASUREMENT_ID=$(echo "$FIREBASE_JSON" | jq -r .measurementId)" >> $GITHUB_ENV
          echo "GOOGLE_WEB_CLIENT_ID=$(echo "$FIREBASE_JSON" | jq -r .googleWebClientId)" >> $GITHUB_ENV

      - name: flutter pub get
        run: flutter pub get

      - name: Build Flutter Web
        run: |
          flutter build web --release --base-href=/ \
            --dart-define=FB_API_KEY="$FB_API_KEY" \
            --dart-define=FB_APP_ID="$FB_APP_ID" \
            --dart-define=FB_PROJECT_ID="$FB_PROJECT_ID" \
            --dart-define=FB_MESSAGING_SENDER_ID="$FB_MESSAGING_SENDER_ID" \
            --dart-define=FB_AUTH_DOMAIN="$FB_AUTH_DOMAIN" \
            --dart-define=FB_STORAGE_BUCKET="$FB_STORAGE_BUCKET" \
            --dart-define=FB_MEASUREMENT_ID="$FB_MEASUREMENT_ID" \
            --dart-define=GOOGLE_WEB_CLIENT_ID="$GOOGLE_WEB_CLIENT_ID"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          cname: caosbox.com
