name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build web (no PWA)
        run: |
          flutter build web --release \
            --base-href=/ \
            --pwa-strategy=none

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          cname: caosbox.com
