name: Deploy Web

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable web
        run: flutter create . --platforms web

      - name: Pub get
        run: flutter pub get

      - name: Build web (dart-define)
        run: |
          flutter build web \
            --release \
            --pwa-strategy=none \
            --base-href=/ \
            --dart-define=FB_API_KEY=${{ secrets.FB_API_KEY }} \
            --dart-define=FB_APP_ID=${{ secrets.FB_APP_ID }} \
            --dart-define=FB_PROJECT_ID=${{ secrets.FB_PROJECT_ID }} \
            --dart-define=FB_MESSAGING_SENDER_ID=${{ secrets.FB_MESSAGING_SENDER_ID }} \
            --dart-define=FB_AUTH_DOMAIN=${{ secrets.FB_AUTH_DOMAIN }} \
            --dart-define=FB_STORAGE_BUCKET=${{ secrets.FB_STORAGE_BUCKET }} \
            --dart-define=FB_MEASUREMENT_ID=${{ secrets.FB_MEASUREMENT_ID }} \
            --dart-define=GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID }}

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          force_orphan: true
