name: Build & Deploy Flutter Web

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.10.0'

      - run: flutter pub get
      - run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "caosbox-ef75b"
          target: "live"
